kind: Project
apiVersion: qts.one/v1beta1
metadata:
  name: argo
spec:
  appProject:
    description: Argo Project
    sourceRepos:
      - "*"
    destinations:
      - namespace: "*"
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    namespaceResourceWhitelist:
      - group: "*"
        kind: "*"
  applications:
    - name: argocd
      repoURL: https://github.com/ibacalu/infra-09.git
      targetRevision: main
      overlays_path: gitops/services/argocd/environments
