kind: Project
apiVersion: qts.one/v1beta1
metadata:
  name: observability
spec:
  appProject:
    description: observability and Data
    sourceRepos:
      - "*"
    destinations:
      - namespace: "*"
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    namespaceResourceWhitelist:
      - group: "*"
        kind: "*"
  applications:
    - name: kube-prometheus-stack
      repoURL: https://github.com/ibacalu/infra-09.git
      targetRevision: main
      overlays_path: gitops/services/kube-prometheus-stack/environments
      namespace: monitoring
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: kube-prometheus-stack-admission
          jqPathExpressions:
            - .webhooks[]?.clientConfig.caBundle
