apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "$(secret:argocd/ghcr#dockerconfigjson|b64enc)"
