- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: argo-workflows-sso
        key: clientSecret
