apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argo-workflows-sso
  namespace: argocd
  labels:
    app.kubernetes.io/name: argo-workflows-sso
    app.kubernetes.io/part-of: argocd
data:
  clientID: $(secret:argocd/argo-workflows-sso#clientID|b64enc)
  clientSecret: $(secret:argocd/argo-workflows-sso#clientSecret|b64enc)
