apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: $(secret:cert-manager/letsencrypt-prod-api-token#email)
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          route53:
            region: $(configmap:argocd/cluster-config#region)
            hostedZoneID: $(configmap:argocd/cluster-config#clusterDNSZoneId)
