apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: Bottlerocket
  role: "$(configmap:argocd/cluster-config#cluster_name)-karpenter-node"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery/$(configmap:argocd/cluster-config#cluster_name): "*"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery/$(configmap:argocd/cluster-config#cluster_name): "*"
  tags:
    Name: karpenter-node
    Organization: "ibacalu"
    Environment: "$(configmap:argocd/cluster-config#environment)"
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand", "spot"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m", "r"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["5"]
      expireAfter: 720h # 30 days
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenUnderutilized
    consolidateAfter: 1m
