apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: argo-events
spec:
  nats:
    native:
      auth: token
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
  namespace: argo-events
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    example:
      port: "12000"
      endpoint: /example
      method: POST
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: dagster-trigger
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        conditions: "test-dep"
        name: dagster-launch
        http:
          url: http://dagster-dagit.dagster.svc.cluster.local/graphql
          method: POST
          payload:
            - src:
                dependencyName: test-dep
                dataKey: body.run_config
              dest: variables.runConfigData
          parameters:
            - src:
                dependencyName: test-dep
              dest: extensions
              operation: overwrite # Just a placeholder for headers/auth
          # The body would be the GraphQL mutation to launch a run.
          # This is a simplifed example showing the connection.
          body: |
            {"query": "mutation LaunchRun { launchPipelineExecution(executionParams: { selector: { repositoryLocationName: \"user-code\", repositoryName: \"deploy_repo\", pipelineName: \"demo_job\" } }) { __typename } }"}
