apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-server-token
  namespace: argocd
  annotations:
    kubernetes.io/service-account.name: argocd-repo-server
type: kubernetes.io/service-account-token
