apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
spec:
  secretName: argocd-tls
  issuerRef:
    kind: ClusterIssuer
    name: $(configmap:argocd/cluster-config#cluster-issuer)
  commonName: cd.$(configmap:argocd/cluster-config#clusterDNSZoneName)
  dnsNames:
    - cd.$(configmap:argocd/cluster-config#clusterDNSZoneName)
