apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: dagster-ksm-alerts
  labels:
    role: alert-rules
spec:
  groups:
  - name: dagster-operations
    rules:
    - alert: DagsterJobFailed
      # Join kube_job_status_failed with kube_job_labels to get Dagster metadata
      expr: |
        kube_job_status_failed{job_name=~"dagster-run-.*"} > 0
        * on(job_name, namespace) group_left(label_dagster_job, label_dagster_run_id, label_dagster_code_location)
        kube_job_labels{job_name=~"dagster-run-.*"}
      for: 1m
      labels:
        severity: critical
        service: dagster
        team: data-engineering
      annotations:
        summary: "Pipeline {{ $labels.label_dagster_job }} failed"
        description: |
          Dagster Run ID {{ $labels.label_dagster_run_id }} has failed.
          
          **Pipeline**: {{ $labels.label_dagster_job }}
          **Run ID**: {{ $labels.label_dagster_run_id }}
          
          Check the Dagster UI for logs and details.
        # Dynamic URL to Dagster UI run page
        runbook_url: "https://dagster.$(configmap:argocd/cluster-config#clusterDNSZoneName)/runs/{{ $labels.label_dagster_run_id }}"
        dashboard_url: "https://grafana.$(configmap:argocd/cluster-config#clusterDNSZoneName)/d/dagster-health"
