apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-auth
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  target:
    name: cloudflare-auth
    creationPolicy: Owner
  data:
  - secretKey: apiToken
    remoteRef:
      key: cloudflare
      property: token
